---
engines:
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
exclude_paths:
  - ".github/"
  - "assets/"
  - "docs/"
  - "packages/**/spec/"
ratings:
   paths:
   - "src/**/**.ts"
